import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { contact, experience, hero } from "@/content";
import { heroView } from "@/lib/selectors";

const repoRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../..",
);

/**
 * public/resume.pdf is generated by scripts/build-resume.py, which keeps its own
 * copy of the bullets. That copy has drifted from the site before: recruiters
 * were reading one story on the page and a different one in the file an ATS
 * parses. Diffing the strings is not as good as diffing the PDF, but it catches
 * the failure that actually happened.
 */
const script = readFileSync(
  path.join(repoRoot, "scripts/build-resume.py"),
  "utf8",
);

describe("resume.pdf matches the site", () => {
  it("carries every experience bullet the page shows", () => {
    const missing = experience.flatMap((entry) =>
      entry.bullets
        .filter((bullet) => !script.includes(bullet))
        .map((bullet) => ({ id: entry.id, bullet })),
    );

    expect(missing).toEqual([]);
  });

  it("carries the Tesla scope line verbatim", () => {
    const tesla = experience.find((entry) => entry.id === "tesla-ai");
    expect(tesla?.scopeLine).toBeTruthy();
    expect(script).toContain(tesla?.scopeLine);
  });

  it("heads with the same title, employer, and location line as the fold", () => {
    expect(script).toContain(`${hero.title} · ${heroView.currentCompany}`);
    expect(script).toContain(heroView.location);
    expect(script).toContain(contact.email);
  });

  it("opens the summary in the recruiter's words, not the Tesla-internal title", () => {
    expect(script).toMatch(/SUMMARY = \(\s*\n\s*"Strategy & Operations and Technical Program Manager\./);
  });
});
